### ISSUE TITLE
can you please translate these error 

### ISSUE THREAD

**Issue by ghost** [josh-gaby/python-plexlibrary#4]
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/user/appdata/python-plexlibrary/plexlibrary/__main__.py", line 8, in <module>
    main()
  File "/mnt/user/appdata/python-plexlibrary/plexlibrary/plexlibrary.py", line 67, in main
    r.run(sort_only=args.sort_only, share_playlist_to_all=args.everyone)
  File "/mnt/user/appdata/python-plexlibrary/plexlibrary/recipe.py", line 711, in run
    missing_items, list_count = self._run(share_playlist_to_all=share_playlist_to_all)
  File "/mnt/user/appdata/python-plexlibrary/plexlibrary/recipe.py", line 649, in _run
    source_libraries = self._get_plex_libraries()
  File "/mnt/user/appdata/python-plexlibrary/plexlibrary/recipe.py", line 164, in _get_plex_libraries
    if 'guid' not in source_library.ALLOWED_FILTERS:
AttributeError: 'MovieSection' object has no attribute 'ALLOWED_FILTERS

**Comment by josh-gaby** [comment]
It looks like the PlexApi has been updated and they have removed the ALLOWED_FILTERS option, I'll update my fork later but for now you could try changing to an older version of plexapi by changing the plexapi line in the requirements.txt file to read plexapi==4.1.0 and running pip install -r requirements.txt again

**Comment by josh-gaby** [comment]
@armin0012002 I have update my fork, if you pull the latest copy of the direct-db-access branch you should no longer get this error.

**Comment by ghost** [comment]
thanks josh your branch update fixed my issue
