### ISSUE TITLE
logs.info(f"{user_name} does not have access to your server.")

### ISSUE THREAD

**Issue by abien** [josh-gaby/python-plexlibrary#5]
What could be causing this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "plexlibrary/__main__.py", line 2, in <module>
    from plexlibrary import main
  File "plexlibrary/plexlibrary.py", line 22, in <module>
    from recipe import Recipe
  File "plexlibrary/recipe.py", line 20, in <module>
    import plexutils
  File "plexlibrary/plexutils.py", line 76
    logs.info(f"{user_name} does not have access to your server.")
```

I assume its something related to playlists but i cant figure out which user its complaining about - or if my token is wrong or if its something else entirely. Please help me to help myself :)

**Comment by josh-gaby** [comment]
Can you share the recipe your trying to run when this happens?

**Comment by josh-gaby** [comment]
I don't use the playlist features of PlexLibrary myself so hadn't done any testing around that.
I've made some changes to the [Python - PlexMovieAgentMapper](https://github.com/josh-gaby/python-plexmovieagentmapper) that the direct-db-access branch of this uses to make it compatible with playlists, that wont fix your issue, which I think is going to be configuration related, but it does mean that playlists work now because it turns out they weren't before.

These changes should at least tell you which user is causing the issue now.

You will need to update using the following commands inside your plexlibrary directory:
git pull
python3 -m pip install -r requirements.txt

**Comment by abien** [comment]
Update fixed the original error. Thanks 👍 

Trying to create an imdbtop250 lib results in something wired though:
The numbering seems to START at 250 (instead of at one)

This is the recipe:
```
# New library details
new_library:
  name: 'Movies Top-250'
  folder: '/mnt/local/Media/Movies/Movies-Top250/'
  sort: true
  sort_title:
    format: '{number}. {title}'
    visible: true
    absolute: true  # Skips numbers for missing items
  # Limit the age (in years) of items to be considered
  # * 0 for no limit
  max_age: 0
  # Maximum number of items to keep in the library
  max_count: 250
  # Remove items that no longer exist in the source lists
  remove_from_library: true

# Weighted sorting (requires TMDb API)
weighted_sorting:
  enabled: false
```

Here is a screenshot of how it looks in Plex: 
![Plex_0uZ1Spejr3](https://user-images.githubusercontent.com/254409/104848251-6417c800-58e4-11eb-9399-589b11370a4b.png)

Not sure about either to post this here or open a new post?

**Comment by josh-gaby** [comment]
Depends on your recipe I think, not sure what sources you have listed but it looks like you don't have the top 249 items it wanted to put in the library.

If you turn off absolute numbering the numbers should start at 1

**Comment by abien** [comment]
I turned it off - it starts at one now. But the numbering is wrong.

Example:
```
[me@mybox] direct-db-access* ± python3 plexlibrary movies_imdb_top_250
2021-01-17 21:23:08,299 INFO:Building lookup hash...
2021-01-17 21:23:10,674 INFO:Running the recipe 'movies_imdb_top_250'
2021-01-17 21:23:10,674 INFO:Retrieving the IMDB list: http://www.imdb.com/chart/top
2021-01-17 21:23:12,083 INFO:Trying to match with items from the 'Movies' library 
2021-01-17 21:23:12,094 INFO:Checking 250 items for 250 max allowed matches.
2021-01-17 21:23:12,094 INFO:
2021-01-17 21:23:12,095 INFO:Trying to match The Shawshank Redemption (1994)
2021-01-17 21:23:12,095 INFO:  Checking the Movies library:
2021-01-17 21:23:12,095 INFO:    Checking with the IMDB id...
2021-01-17 21:23:12,095 INFO:    ... looks like we've found a match
2021-01-17 21:23:12,095 INFO:1 The Shawshank Redemption (1994)
2021-01-17 21:23:12,095 INFO:
2021-01-17 21:23:12,095 INFO:Trying to match The Godfather (1972)
2021-01-17 21:23:12,095 INFO:  Checking the Movies library:
2021-01-17 21:23:12,096 INFO:    Checking with the IMDB id...
2021-01-17 21:23:12,096 INFO:    ... looks like we've found a match
2021-01-17 21:23:12,096 INFO:2 The Godfather (1972)
2021-01-17 21:23:12,096 INFO:
2021-01-17 21:23:12,096 INFO:Trying to match The Godfather: Part II (1974)
2021-01-17 21:23:12,096 INFO:  Checking the Movies library:
2021-01-17 21:23:12,096 INFO:    Checking with the IMDB id...
2021-01-17 21:23:12,097 INFO:    ... looks like we've found a match
2021-01-17 21:23:12,097 INFO:3 The Godfather: Part II (1974)
2021-01-17 21:23:12,097 INFO:
2021-01-17 21:23:12,097 INFO:Trying to match The Dark Knight (2008)
2021-01-17 21:23:12,097 INFO:  Checking the Movies library:
2021-01-17 21:23:12,097 INFO:    Checking with the IMDB id...
2021-01-17 21:23:12,097 INFO:    ... looks like we've found a match
(...)
2021-01-17 21:23:12,264 INFO:Creating symlinks for 246 matching items in the library...
(...)
2021-01-17 21:23:14,267 INFO:Created symlinks for 0 new items:
2021-01-17 21:23:14,267 INFO:Creating the 'Movies Top-250' library in Plex...
2021-01-17 21:23:14,274 WARNING:Library already exists in Plex. Scanning the library...
2021-01-17 21:23:14,278 INFO:Waiting for metadata to finish downloading...
2021-01-17 21:23:19,299 INFO:Retrieving a list of items from the 'Movies Top-250' library in Plex...
2021-01-17 21:23:20,792 INFO:Setting the sort titles for the 'Movies Top-250' library...
2021-01-17 21:23:20,793 INFO:Removing symlinks for items which no longer qualify 
2021-01-17 21:23:20,809 INFO:Removed symlinks for 0 items.
2021-01-17 21:23:20,809 INFO:Scanning the 'Movies Top-250' library...
2021-01-17 21:23:32,246 INFO:1 1. Toy Story (1995)
2021-01-17 21:23:32,257 INFO:2 2. Toy Story 3 (2010)
2021-01-17 21:23:32,811 INFO:3 3. Trainspotting (1996)
```

No1 should be The Shawshank Redemption - not Toy Story. Any ideas?

**Comment by josh-gaby** [comment]
If you can share your recipe I can take a look at it

**Comment by abien** [comment]
Sure, here we go:

```
[sysadmin@cloudbox:/opt/python-plexlibrary] direct-db-access* ± cat recipes/movies_imdb_top_250.yml
# Supported types: movie, tv
library_type: 'movie'

# Source list(s)
source_list_urls:
  - 'http://www.imdb.com/chart/top'

# Source library details
source_libraries:
  - name: 'Movies'
    folders:
      - '/data/Movies/Movies-ALL'

# New library details
new_library:
  name: 'Movies Top-250'
  folder: '/mnt/local/Media/Movies/Movies-Top250/'
  sort: true
  sort_title:
    format: '{number}. {title}'
    visible: false
    absolute: false  # Skips numbers for missing items
  # Limit the age (in years) of items to be considered
  # * 0 for no limit
  max_age: 0
  # Maximum number of items to keep in the library
  max_count: 250
  # Remove items that no longer exist in the source lists
  remove_from_library: true

# Weighted sorting (requires TMDb API)
weighted_sorting:
  enabled: false
  better_release_date: false
  weights:
    # Think of these as percentages,
    # but they don't have to add up to 1.0
    # * Additive
    # * Higher value -> more important
    index: 0.0
    vote: 0.0
    age: 0.0
    random: 0.0
    # Penalize (<0) or reward (>0) certain (TMDb) genres
    # * Final weight is multipled by these values
    genre_bias:
      'TV Movie': 0.7
      'Animation': 0.95
debugging:
  enabled: true
```

**Comment by josh-gaby** [comment]
Not sure exactly why yours isn't working sorry, I only added the code that makes it work with the new Plex Media Agent. 
I'm working at the moment but I'll take a look tonight to see why the IMDB list by itself doesn't work and make some changes to this fork.

I do have a top 250 setup running on my sever, it's using a Trakt URL but that's the only difference I can see:

```
# Supported types: movie, tv
library_type: 'movie'
debugging:
  enabled: true

# Source list(s)
# * Experiment with the limits and order of the URLs below
#   to get a different balance.
source_list_urls:
  - 'https://api.trakt.tv/users/justin/lists/imdb-top-rated-movies/items/movies'

# Source library details
source_libraries:
  - name: 'Movies'
    folders:
      - '/nfs/Storage/Movies'

# New library details
new_library:
  name: 'Movies - IMDB Top 250'
  folder: '/mnt/plex/sorted/Movies IMDB Top 250'
  sort: true
  sort_title:
    format: '{number}. {title}'
    visible: false
    absolute: true  # Skips numbers for missing items
  # Limit the age (in years) of items to be considered
  # * 0 for no limit
  max_age: 0
  # Maximum number of items to keep in the library
  max_count: 250
  # Remove items that no longer exist in the source lists
  remove_from_library: true

# Weighted sorting (requires TMDb API)
weighted_sorting:
  enabled: false
  better_release_date: false
  weights:
    # Think of these as percentages,
    # but they don't have to add up to 1.0
    # * Additive
    # * Higher value -> more important
    index: 0.70
    vote: 0.10
    age: 0.15
    random: 0.05
    # Penalize (<0) or reward (>0) certain (TMDb) genres
    # * Final weight is multipled by these values
    genre_bias:
      'TV Movie': 0.7
      'Animation': 0.95
```

**Comment by abien** [comment]
The sort/ordering of the imdb250 is all over the place and its nowhere near the IMDB-TOP-250 list.
Since this issue was originally about something else which is fixed i will close it now.
I ended up not using the imdb top250 at all.

**Comment by josh-gaby** [comment]
@abien Closing this reminded me I needed to take another look at this.

I've the same IMDB source as you have and my list is ordered correctly, the only thing that is different in my current recipe is I have "absolute" set to true under "sort_title".

I also removed the rate limiting for TMDB api since they disabled their rate limit back in 2019 so if you wanted to do a git pull and try this again it'll be a lot quicker.

My current recipe that results in correct ordering for me:
```
# Supported types: movie, tv
library_type: 'movie'
debugging:
  enabled: true

# Source list(s)
# * Experiment with the limits and order of the URLs below
#   to get a different balance.
source_list_urls:
  - 'http://www.imdb.com/chart/top'

# Source library details
source_libraries:
  - name: 'Movies'
    folders:
      - '/nfs/Storage/Movies'

# New library details
new_library:
  name: 'Movies - IMDB Top 250'
  folder: '/mnt/plex/sorted/Movies IMDB Top 250'
  sort: true
  sort_title:
    format: '{number}. {title}'
    visible: false
    absolute: true  # Skips numbers for missing items
  # Limit the age (in years) of items to be considered
  # * 0 for no limit
  max_age: 0
  # Maximum number of items to keep in the library
  max_count: 250
  # Remove items that no longer exist in the source lists
  remove_from_library: true

# Weighted sorting (requires TMDb API)
weighted_sorting:
  enabled: false
  better_release_date: false
  weights:
    # Think of these as percentages,
    # but they don't have to add up to 1.0
    # * Additive
    # * Higher value -> more important
    index: 0.70
    vote: 0.10
    age: 0.15
    random: 0.05
    # Penalize (<0) or reward (>0) certain (TMDb) genres
    # * Final weight is multipled by these values
    genre_bias:
      'TV Movie': 0.7
      'Animation': 0.95
```
